auth0:
  audience: "https://your-api.example.com"
  domain: "your-auth0-domain.auth0.com"
server:
  address: ":80"
  readTimeout: "15s"
  writeTimeout: "15s"
  idleTimeout: "15s"
  maxHeaderBytes: 1048576
  releaseStage: "local"
  logRequests: false
  logLevel: "info"
subrouters:
  - targetUrl: http://0.0.0.0:4196/private
    prefix: "/private"
    stripPrefix: true
    name: Private endpoint
    authorizationConfig:
      requiredScopes:
      - access:private
    auth: true
    gzip: true
    cors:
      allowCredentials: true
      allowedOrigins:
      - "*"
      allowedHeaders:
      - Authorization
      - Content-Type
  - targetUrl: http://0.0.0.0:4196/public
    prefix: "/public"
    stripPrefix: true
    name: Public endpoint
    authorizationConfig:
      requiredScopes:
      - access:public
    auth: true
    gzip: true
    cors:
      allowCredentials: true
      allowedOrigins:
      - "*"
      allowedHeaders:
      - Authorization
      - Content-Type
