// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IReverseProxyHandler is an autogenerated mock type for the IReverseProxyHandler type
type IReverseProxyHandler struct {
	mock.Mock
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *IReverseProxyHandler) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// NewIReverseProxyHandler creates a new instance of IReverseProxyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIReverseProxyHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IReverseProxyHandler {
	mock := &IReverseProxyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
