// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewIReverseProxyHandler creates a new instance of IReverseProxyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIReverseProxyHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IReverseProxyHandler {
	mock := &IReverseProxyHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IReverseProxyHandler is an autogenerated mock type for the IReverseProxyHandler type
type IReverseProxyHandler struct {
	mock.Mock
}

type IReverseProxyHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *IReverseProxyHandler) EXPECT() *IReverseProxyHandler_Expecter {
	return &IReverseProxyHandler_Expecter{mock: &_m.Mock}
}

// ServeHTTP provides a mock function for the type IReverseProxyHandler
func (_mock *IReverseProxyHandler) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// IReverseProxyHandler_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type IReverseProxyHandler_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *IReverseProxyHandler_Expecter) ServeHTTP(responseWriter interface{}, request interface{}) *IReverseProxyHandler_ServeHTTP_Call {
	return &IReverseProxyHandler_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", responseWriter, request)}
}

func (_c *IReverseProxyHandler_ServeHTTP_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *IReverseProxyHandler_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IReverseProxyHandler_ServeHTTP_Call) Return() *IReverseProxyHandler_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *IReverseProxyHandler_ServeHTTP_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *IReverseProxyHandler_ServeHTTP_Call {
	_c.Run(run)
	return _c
}
