// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	cors "github.com/greencoda/auth0-api-gateway/internal/middleware/cors"
	mock "github.com/stretchr/testify/mock"

	subrouter "github.com/greencoda/auth0-api-gateway/internal/config/subrouter"
)

// ICORSFactory is an autogenerated mock type for the ICORSFactory type
type ICORSFactory struct {
	mock.Mock
}

// NewCORS provides a mock function with given fields: config
func (_m *ICORSFactory) NewCORS(config subrouter.CORSConfig) cors.ICORS {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for NewCORS")
	}

	var r0 cors.ICORS
	if rf, ok := ret.Get(0).(func(subrouter.CORSConfig) cors.ICORS); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cors.ICORS)
		}
	}

	return r0
}

// NewICORSFactory creates a new instance of ICORSFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICORSFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICORSFactory {
	mock := &ICORSFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
