// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	mux "github.com/gorilla/mux"
	mock "github.com/stretchr/testify/mock"
)

// IAuth0ScopeValidator is an autogenerated mock type for the IAuth0ScopeValidator type
type IAuth0ScopeValidator struct {
	mock.Mock
}

// Handler provides a mock function with no fields
func (_m *IAuth0ScopeValidator) Handler() mux.MiddlewareFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 mux.MiddlewareFunc
	if rf, ok := ret.Get(0).(func() mux.MiddlewareFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mux.MiddlewareFunc)
		}
	}

	return r0
}

// NewIAuth0ScopeValidator creates a new instance of IAuth0ScopeValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuth0ScopeValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuth0ScopeValidator {
	mock := &IAuth0ScopeValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
