name: Test and push

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: greencoda/auth0-api-gateway

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.5
        check-latest: true

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.3.0
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.5
        check-latest: true

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a cmd/main.go 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.5
        check-latest: true
        
    - name: Setup Dependencies
      run: go mod tidy && git diff-index --quiet HEAD || { >&2 echo "Stale go.{mod,sum} detected. This can be fixed with 'go mod tidy'."; exit 1; }

    - name: Run Test
      run: go test -v -coverprofile=coverage.out $(go list ./... | grep -v '/mocks/\|/tools/\|/cmd\|/module')

    - name: Copy coverage.out file to temp
      run: cp coverage.out $RUNNER_TEMP
      
    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        coverage-file: ${{ runner.temp }}/coverage.out
        report: true
        chart: true
        amend: true
      if: |
        github.event_name == 'push'
      continue-on-error: true

  docker:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max